thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  mode: HTML5

line-notify:
  client-id: ${LINE_NOTIFY_CLIENT_ID:}
  client-secret: ${LINE_NOTIFY_CLIENT_SECRET:}
